apiVersion: v1
kind: Service
metadata:
  name: camera-assignments
  labels:
    app: camera-assignments
spec:
  selector:
    app: camera-assignments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  # Change to LoadBalancer if you want a direct external IP:
  # type: LoadBalancer
  type: ClusterIP
